### ISSUE TITLE
Hot reload not working.

### ISSUE THREAD

**Issue by risonsimon** [davezuko/react-redux-starter-kit#188] opened 2015-11-19 15:41 UTC
I cloned the repository and installed dependencies.
I started the dev server with `npm start`.
Tried to edit `HomeView.js`. Nothing happens.
Edited `counter.js` in `reducers`. Not updated in front end.

However in my browser console, I get the following.
![image](https://cloud.githubusercontent.com/assets/871227/11275032/7ea1623e-8eba-11e5-9826-0f4bb9a20009.png)
The webpack dev server is not restarting though.

**Comment by davezuko** [comment] 2015-11-19 16:34
Oh that's lame, let me give a try locally in a bit to see if I can reproduce.

**Comment by davezuko** [comment] 2015-11-19 16:43
I can't manage to reproduce this; both reducer and component hot reloading seem to be working as expected. What system and node version are you on?

![hot_reload](https://cloud.githubusercontent.com/assets/6439050/11277047/b252ddf4-8eb2-11e5-9f3b-969218657dcf.gif)

**Comment by risonsimon** [comment] 2015-11-19 16:48
**Node version**:
v4.2.2

**My system info**:
![image](https://cloud.githubusercontent.com/assets/871227/11277144/fcdb1c54-8ec3-11e5-96ac-f9463ea863df.png)

**Browser**:
Chrome Version 46.0.2490.71 (64-bit)

**Comment by risonsimon** [comment] 2015-11-19 16:49
**Node version**:
v4.2.2

**System info**:
Ubuntu 14.04 64bit

**Browser info**:
Version 46.0.2490.71 (64-bit)

Any other info you need?

**Comment by davezuko** [comment] 2015-11-19 16:50
Thanks. Just curious, are there any other projects you've used where HMR works (and that use react-transform-hmr, not react-hot-loader)?

**Comment by risonsimon** [comment] 2015-11-19 17:46
In this project, it worked for me once yesterday. But its been inconsistent. I don't know what caused it to work either. But it hasn't worked since.

**Comment by melodylu** [comment] 2015-11-19 22:29
Hotreload is working great on my system as of 11/19/26, commit `1a9fc9a`.
- [x] git clone to local
- [x] cd into react-redux-starter-kit
- [x] `npm install`
- [x] `npm start`
- [x] changed HomeView.js, saved, **clicked in chrome to make the window active**.


Changes appeared without reload, but maybe that last step makes a difference?

![image](https://cloud.githubusercontent.com/assets/7496190/11286371/7bc85fea-8ec9-11e5-921c-bc9649507dfa.png)

**Comment by risonsimon** [comment] 2015-11-20 21:06
Its not working, I cloned another copy and tried again. 

I'm getting hmr enabled in my browser console though.

**Comment by davezuko** [comment] 2015-11-21 14:53
@risonsimon I might try putting together a minimal hot-reload example and see if you have issues with that, since at this point I really don't know what could be causing the issue.

**Comment by davezuko** [comment] 2015-11-24 13:54
@risonsimon and @saem can you clone https://github.com/davezuko/react-redux-hot-minimal-example and see if hot reloading works for you?

And by hot reloading, there are two pieces: component reloading and reducer replacement. It would help if we could narrow it down and figure it if it's both or just one of the two.

**Comment by risonsimon** [comment] 2015-11-24 14:13
@davezuko  I cloned and tested the following repos and hot reload was working fine for both components and reducers.

1. https://github.com/davezuko/react-redux-hot-minimal-example
2. https://github.com/gaearon/react-hot-boilerplate

**Comment by davezuko** [comment] 2015-11-24 14:18
@risonsimon thanks. My best guess right now is that it either has to do with the vendor bundle or with redux-router. Give me a minute to make another branch and we can go from there.

**Comment by risonsimon** [comment] 2015-11-24 14:20
weirdly hot reload started working for me now after testing these two repos!! Don't know if it'll stop working later.

**Comment by davezuko** [comment] 2015-11-24 14:25
That's so strange... interested to see what @saem has to say.

**Comment by davezuko** [comment] 2015-11-25 14:59
@risonsimon is it still working for you?

**Comment by risonsimon** [comment] 2015-11-25 15:15
yes it is!

**Comment by davezuko** [comment] 2015-11-25 15:17
I was half hoping it wasn't haha, but glad it is. @saem if you can confirm that it's working for you I'd like to close this ticket out, since I'm at a complete loss.

**Comment by saem** [comment] 2015-11-25 21:05
I can look at this tonight, as it's on my home machine, in about 6 hours.

**Comment by saem** [comment] 2015-11-26 03:26
Ok, so I checked my install log, and I had some npm module install issues. I fixed that up, ran npm install again after remove node_modules, and it still didn't work.

Did another git pull, saw package.json was updated, re-ran npm install (didn't remove node_modules), and it works! The output of the npm install was the following, so I'm guessing that was the issue.

```
postcss-loader@0.8.0 node_modules/postcss-loader
├── loader-utils@0.2.12 (big.js@3.1.3, json5@0.4.0)
└── postcss@5.0.12 (js-base64@2.1.9, source-map@0.5.3, supports-color@3.1.2)
```

**Comment by davezuko** [comment] 2015-11-26 13:51
Weird, not sure why that would fix it but if it works it works. Closing for now.

**Closed by davezuko** 2015-11-26 13:51 UTC
Labels: bug

**Comment by janoist1** [comment] 2016-05-12 16:34
Hi there,
I'm facing the same issue with HMR not doing its job ..
I tried this: https://github.com/davezuko/react-redux-hot-minimal-example - which was working perfectly
Any idea? Thanks!

**Comment by davezuko** [comment] 2016-05-12 16:39
@janoist1 it's been changed recently while we await integration with React Hot Loader v3. For now you will lose your component state (but not app state) on changes. If you want to use `react-transform-hmr` you can use the `2.x` tag.

**Comment by janoist1** [comment] 2016-05-12 17:04
Thanks for the quick reply!
I've just checked out the v2.0.0, removed/reinstalled the node_modules ... but no luck
I'm using vagrant for the dev box, so that I updated the host to listen on the correct address (note: why don't you put the host into an env variable like you did with the port?). Do I need to edit something else.. ? thanks

**Comment by janoist1** [comment] 2016-05-13 09:31
Dave, what do you think shall I just wait for the v3 to be ready or is it going to take a long time and better look for a solution?

**Comment by janoist1** [comment] 2016-05-13 09:35
It is working now .. Don't know what I was doing wrong. 👍  :)

**Comment by janoist1** [comment] 2016-05-13 11:00
After some more investigation it turned out that the reloader only works if I make the changes inside the Vagrant box. The host machine is a Mac. Is there any fix for this?

**Comment by PhilBroadbent** [comment] 2017-03-23 07:04
I'm seeing this issue now - has anyone else reported it recently @davezuko?
I've cloned the repo a few times, fixed react-router to 3.0.0 in case it was that, but have been unable to get it working. Any advice please?

**Node version:**
v7.5.0

**System Info:**
Mac OSX El Capitan 10.11.6

**Browser info:**
Google Chrome Version 57.0.2987.110 (64-bit)

**Comment by davezuko** [comment] 2017-03-23 12:24
@PhilBroadbent there is no longer a React Hot Loader, just normal webpack hot reload. When your source code changes, the entire application should be remounted with the global redux state preserved. If you're not seeing that work then there's something amiss.

**Comment by PhilBroadbent** [comment] 2017-03-23 22:38
Strange - nope, I'm not seeing that when checking out the latest code. Perhaps a latest version of something has caused this? Any ideas please?
