### ISSUE TITLE
EPEERINVALID: eslint@2.0.0-rc.0 does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by timfpark** [davezuko/react-redux-starter-kit#570] opened 2016-02-17 02:29 UTC
When doing an 'npm install', installing eslint fails with:  

npm ERR! Darwin 15.2.0
npm ERR! argv "/Users/tim/.nvm/versions/node/v4.2.6/bin/node" "/Users/tim/.nvm/versions/node/v4.2.6/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v2.14.12
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package eslint@2.0.0-rc.1 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer eslint-config-standard@5.1.0 wants eslint@^2.0.0-rc.0
npm ERR! peerinvalid Peer eslint-plugin-babel@3.1.0 wants eslint@>=1.0.0
npm ERR! peerinvalid Peer eslint-config-standard-react@2.3.0 wants eslint@^2.0.0-rc.0
npm ERR! peerinvalid Peer eslint-loader@1.2.1 wants eslint@^1.6.0

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/tim/dev/rhom/webapp3/npm-debug.log

**Comment by mmmoli** [comment] 2016-02-17 10:27
:thumbsup: Found this last night too

**Comment by christiansakai** [comment] 2016-02-17 11:44
I encountered this when I am using npm 2. if I am using npm 3 it is fine

**Comment by davezuko** [comment] 2016-02-17 13:57
Please try with npm 3, sadly I've dropped support for npm 2 since it's just too much work to keep up with everything. Closing as dupe of a previous issue, but will re-open if npm 3 does not solve it. Thanks!

**Closed by davezuko** 2016-02-17 13:57 UTC
