### ISSUE TITLE
deploy on static pages with relative paths 

### ISSUE THREAD

**Issue by maanenh** [davezuko/react-redux-starter-kit#877] opened 2016-06-21 22:09 UTC
Is there an easy way to deploy the production code (`npm run deploy:prod`) on a static website (for example `username.github.io/projectname`

I see two issues:

- app does not work when not deployed on the root
- routes: when navigated to 'counter' refresh of the page does not work

**Comment by jakegibson** [comment] 2016-06-22 01:18
I deployed to s3 without issues.  If you aren't on the root just update your config compiler_public_path.  On s3 I had to set the error route to index.html to keep the react router intact.

**Comment by davezuko** [comment] 2016-06-22 03:24
Also make sure you are setting the `basename`, see: https://github.com/davezuko/react-redux-starter-kit/issues/852

**Comment by davezuko** [comment] 2016-06-22 03:24
Closing as a duplicate of https://github.com/davezuko/react-redux-starter-kit/issues/852, but if you still can't resolve it ping me and we can reopen.

**Closed by davezuko** 2016-06-22 03:24 UTC

**Comment by maanenh** [comment] 2016-06-23 19:59
Thanks a lot:,
I changed two things to get it working:
* in index.js:  \_\_BASENAME\_\_ with the subpath including __preceeding slash!__
* in environments.js: compiler_public_path  with empty string
