### ISSUE TITLE
speed up test build time breaks Codeship CI

### ISSUE THREAD

**Issue by GerritWanderer** [davezuko/react-redux-starter-kit#572] opened 2016-02-17 15:49 UTC
Hey Devs,

after we merged the latest improvements regarding the test build time (commit 998cce613f42beb7db21cec79f32f13686acfc66), we recognized that our builds on Codeship CI are failing due to an `SyntaxError: Expected token ']'` error.
On our local machines (MacOSX and Ubuntu with PhantomJS 2.1.1) it works fine to run the tests though.

I can also easily reproduce this error, when I fork the original react-redux-starter-kit master and connect it with codeship. It breaks with this error and I assume it belongs to the karma-webpack-with-fast-source-maps package.

Screenshot is attached:
![bildschirmfoto 2016-02-17 um 16 41 42](https://cloud.githubusercontent.com/assets/226185/13114993/444f46fa-d596-11e5-8b79-7828c18476ee.png)

Any hints?

**Comment by davezuko** [comment] 2016-02-17 15:56
Having never used Codeship, is there anything different about its environment than yours? I just signed up for Codeship and will try to reproduce, but it seems incredibly strange that this only occurs in that environment. On a related note, I also merged those same fixes into our applications at work (CircleCI) and we haven't run into any issues.

Will try to repro on Codeship and see how it goes.

**Comment by GerritWanderer** [comment] 2016-02-18 12:23
No, never had the feeling that the codeship environment is different from ours. Thanks for investigating this issue.

**Comment by davezuko** [comment] 2016-02-18 16:13
Well, reproducing at least: https://codeship.com/projects/134857/builds/12222450

**Comment by Pintouch** [comment] 2016-03-24 13:48
I have the same error on CodeShip.

I think that is because the phantomjs version on codeship servers is "1.9.7", and on local I use "2.1.1".
I'm trying to make a script to update the phantomjs version on the CodeShip server. 
I let you know if I find something.

**Comment by Pintouch** [comment] 2016-03-24 14:36
Installing phantomjs 2.1.1 before running test solved the issue above but now, the build silently fails without any error...
![group](https://cloud.githubusercontent.com/assets/5173681/14020120/f0f123d2-f1d5-11e5-8182-517b886d6caf.png)

I'll continue investigating, if you have some ideas, let me know.

**Comment by adrianObel** [comment] 2016-04-07 14:32
I'm having the exact same problem when running tests on Codeship. Mine although is running on Phantom 2.1.1.
```
PhantomJS 2.1.1 (Linux 0.0.0) ERROR
SyntaxError: Expected token ']'
```
from `test-bundler.js`

**Comment by jeremyw** [comment] 2016-04-08 21:57
Could this be related to https://github.com/eslint/eslint/issues/2228?

**Comment by gerbal** [comment] 2016-04-11 14:43
Same Issue running tests inside a local Docker image

**Comment by gerbal** [comment] 2016-04-11 14:50
I don't know what the cause of this was, but I resolved it by changing this line https://github.com/davezuko/react-redux-starter-kit/blob/master/tests/test-bundler.js#L23

from:  
```es6
const __karmaWebpackManifest__ = [] // eslint-disable-line
```

to:  
```es6
const __karmaWebpackManifest__ = new Array() // eslint-disable-line
```

**Comment by davezuko** [comment] 2016-04-11 15:13
@gerbal that's _so_ strange to me. Especially that it would only cause issues in very particular environments.

**Comment by davezuko** [comment] 2016-04-13 22:29
All hail @gerbal .

Fixed with https://github.com/davezuko/react-redux-starter-kit/pull/709.

**Closed** 2016-04-13 22:28 UTC
Labels: Needs Investigation

**Comment by GerritWanderer** [comment] 2016-04-14 13:37
Thank you @gerbal for your investigation.
