### ISSUE TITLE
Error when calling super()

### ISSUE THREAD

**Issue by patrickheeney** [davezuko/react-redux-starter-kit#256] opened 2015-12-11 02:35 UTC
After updating my starter kit to match, I am getting this error in production when running npm run start. It seems to be caused by my React class calling the super constructor. The base starter kit doesn't seem to call super yet, but you will definitely run into this error after adding a few React components on top of the base. 

```
return obj && typeof _symbol2.default !== "undefined" && obj.constructor === _symbol2.default ? "symbol" : typeof obj === "undefined" ? "undefined" : (0, _typeof3.default)(obj);
```

Seemed to have tracked it here: https://phabricator.babeljs.io/T6670 and here: https://phabricator.babeljs.io/T6644. The cause seems to be updating the babel-runtime.

**Comment by davezuko** [comment] 2015-12-11 03:03
Oh that's awful, thanks for pointing that out. I figured it was best for the kit to get to Babel 6 ASAP and then work out the pain points over time, but that's pretty nasty. Should probably create an issue label specifically for "known babel issue".

**Comment by justingreenberg** [comment] 2015-12-11 07:30
@patrickheeney @davezuko this should be fixed with next release, see: babel/babel#3142

**Comment by patrickheeney** [comment] 2015-12-11 17:04
I found another problem with babel6, but I haven't found it upstream yet. This is the use case and workaround:

```
//test/Test.js
class Test{}
export default Test;

//test/index.js
export {default as Test} from './Test';

//app.js
import { Test } from './test';
new Test()

//Error: Test is not a function
```

Workaround:

```
//test/index.js
import Test from './Test';
export { Test };
```

Seems to be related to various issues around `default` exports.

**Comment by patrickheeney** [comment] 2015-12-11 17:12
@davezuko @justingreenberg I patched my environment using that fix proposed in babel/babel#3142 . I tested the steps individually but not the whole script. The starterkit is now fully working for me.

Patch: https://gist.github.com/patrickheeney/0e7f6324457d0c786acb

**Comment by justingreenberg** [comment] 2015-12-11 17:39
@patrickheeney thank you for following up! that's good news—#3142 fixes this issue :) 

the cause is a messy combination of npm3's peerDeps, babel's new monorepo design and mostly the fact that `babel-runtime` was not properly tracking it's siblings—using incorrect references to helper functions, creating cyclic references, etc. 

of note: the 5.x version of `babel-runtime` (required by 6.x) was not updated to leverage peerDeps. there were literally 73 `babel-runtime`s in `node_moduels` before i ran `npm dedupe` last night. 

anyway this is a serious issue and authors seem to on it. hopefully they get it merged today.

**Comment by neverfox** [comment] 2015-12-13 07:37
A lot of things about Babel 6 are really starting to piss me off lol. Apparently this was never meant to be allowed (allowed by 5, now "fixed" by 6):

a.js
```
export default { foo };
```
b.js
```
import { foo } from 'a'
// foo is undefined
// must explicitly export named exports,
// as they are not longer inferred from keys on default export
```

The number of places I've seen that used (including my own code) is mind-boggling. A lot of people will be patching libraries. In any case, I ran into the _typeof3.default bug because I was doing something like this:

utils/PropTypes.js
```
import { PropTypes } from 'react'
export default {
  ...PropTypes,
  // some custom PropTypes
}
```
utils/index.js
```
//...
export PropTypes from './PropTypes.js'
//...
```
Looks totally legit right? Well, it was in 5. But this bug requires that I export it as anything *but* PropTypes.

**Comment by neverfox** [comment] 2015-12-13 07:42
@patrickheeney I tried your patch but I get a slew of errors about `Unknown option: /mypath/.babelrc.presets`

**Comment by patrickheeney** [comment] 2015-12-13 07:48
@neverfox Hmm, definitely sounds odd. At what step?

To add to what you mentioned above, I also ran into this:

```
class Test {}
export default Test;

// used to work in babel5
const someVar = 'Test';
const test = require(`./${someVar}`};

// now it seems to be
const test = require(`./${someVar}`}.default
```

Something about `module.exports` was removed so you have to explicitly target `.default` now.

**Comment by neverfox** [comment] 2015-12-13 07:52
@patrickheeney As soon as the make starts, on every file. It finally says the build it complete and then it errors out with:

```
Cannot find module '/mypath/node_modules/babel-patch/packages/babel-polyfill/lib/index.js'
```

**Comment by patrickheeney** [comment] 2015-12-13 07:57
@neverfox Odd, I have to run for now, but have a look at https://github.com/loganfsmyth/babel/blob/runtime-typeof-error-T6644/Makefile . Maybe try `make bootstrap` first or running the dependencies like `learna` manually in case it is missing something.

**Comment by neverfox** [comment] 2015-12-13 08:01
I may have to cut my losses for now and just strip out Babel 6 until they get the kinks out of it. It doesn't feel fully baked yet.

**Comment by justingreenberg** [comment] 2015-12-14 07:48
babel/babel#3142 was just merged, so these issues should be fixed with next release

**Comment by neverfox** [comment] 2015-12-14 07:48
Just got the notice too. :+1:

**Comment by neverfox** [comment] 2015-12-14 19:06
Unfortunately, the submitter deleted the branch the patch was using, so we're in limbo, unable to patch, until they release.

**Comment by patrickheeney** [comment] 2015-12-14 19:11
I have a backup of my patched version: https://www.dropbox.com/s/agt8xv89721z6vr/babel-runtime.7z?dl=0 . Alternatively you could probably modify my `patch.sh` to pull from babel and that commit instead of the previous branch.

**Comment by justingreenberg** [comment] 2015-12-14 19:17
they will probably release a new version before i finish typing this comment

**Comment by neverfox** [comment] 2015-12-14 19:31
As for why the patch was never working, it's because it doubles up on `/node_modules/` for every path, e.g. `.../node_modules/node_modules/babel-patch/...`.

**Comment by patrickheeney** [comment] 2015-12-14 19:33
@neverfox Good to know. I never tested the patch in its entirety, just documented the general steps in case I needed to do it again.

**Comment by neverfox** [comment] 2015-12-14 19:52
@patrickheeney Thanks for the archive. That got me over the hump for now.

**Comment by neverfox** [comment] 2015-12-15 02:17
Woohoo! https://github.com/babel/babel/releases/tag/v6.3.19

**Comment by justingreenberg** [comment] 2015-12-15 02:29
this is interesting so i'll share... 

i didn't understand why `babel-core` was still shipping with babel-runtime 5 as a dependency: 
https://github.com/babel/babel/blob/master/packages/babel-core/package.json#L32

apparently the new `babel-runtime` doesn't care and just transforms all the requires to point to itself: 
https://github.com/babel/babel/pull/3142/files#diff-0bd3e5a73a7b1b450d528b2fd9346a33R87

pretty cool

**Comment by neverfox** [comment] 2015-12-15 03:58
Funny you mention that. They just posted on the issue tracker `This should be all set if you load babel-runtime@6.3.19`

**Comment by justingreenberg** [comment] 2015-12-15 07:34
if you're interested i tracked down the tool they use internally for versioning and publishing management.... monorepo design is starting to make more sense https://github.com/sebmck/lerna

**Closed** 2015-12-15 14:12 UTC
Labels: babel 6 issue: awaiting fix
