### ISSUE TITLE
Material-UI causes failure

### ISSUE THREAD

**Issue by JasonWeise** [davezuko/react-redux-starter-kit#318] opened 2015-12-16 10:37 UTC
Hi

I am testing your excellent react/redux starter for a new project and have come up with an issue.
When adding Material-UI to packages.json and importing something from material-ui into one of the view components and try to compile production, I am receiving the following error.
````
npm ERR! Darwin 15.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "compile" "--production"
npm ERR! node v5.2.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@0.18.0 compile: `node -r dotenv/config --harmony bin/compile`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-redux-starter-kit@0.18.0 compile script 'node -r dotenv/config --harmony bin/compile'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-redux-starter-kit package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node -r dotenv/config --harmony bin/compile
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-redux-starter-kit
npm ERR! There is likely additional logging output above.

````
I am on node 5.2.0 on OSX (El Capitan).
If I remove import { RaisedButton } from 'material-ui' from the view component it compiles fine.

To clarify what I am doing, I have simply imported a simple RaisedButton component into the About View of you framework example and this is where I recieve the error.

I have developed React Apps with Material-UI previously so believe all my side is ok (considering it is such as simple test).

Any advice would be appreciated :)

**Comment by sarunast** [comment] 2015-12-16 13:03
I am using material ui with no problems. With latest changes.

**Comment by sarunast** [comment] 2015-12-16 13:12
Try running command directly from terminal : `node -r dotenv/config --harmony bin/compile`

**Comment by neverfox** [comment] 2015-12-16 16:39
Hmm, I'm using material-ui just fine with the latest kit. What version of material-ui are you using?

**Comment by davezuko** [comment] 2015-12-20 15:26
@JasonWeise any updates on this?

**Comment by davezuko** [comment] 2015-12-22 16:29
Closing this since we need more information around this problem. If you're still having issues please feel free to submit more information and we can re-open.

**Comment by tyleriguchi** [comment] 2016-01-21 23:02
@davezuko Hey I'm actually running into this problem as well. I'm running material-ui 0.14.2 with node 4.2.1 and npm 3.5.2. When I run the node environment as development it work, but staging and production results in `node -r dotenv/config --harmony bin/compile` throwing an error.

**Comment by neverfox** [comment] 2016-01-22 00:01
I use material-ui in all of my projects, and haven't seen any issues, but I'll make sure I'm up-to-date and try again.

**Comment by tyleriguchi** [comment] 2016-01-22 00:13
@neverfox what versions are you running? I'm using 1.0 for the starter kit, material ui 0.14.2, node 5.5.0, npm 3.5.2 on Maverick. What other info are you thinking?

**Comment by neverfox** [comment] 2016-01-22 02:14
In particular, what components from MUI you're using and whether or not you think it's caused by one in particular or MUI in general.

**Comment by davezuko** [comment] 2016-01-23 17:38
Referencing https://github.com/davezuko/react-redux-starter-kit/issues/318

**Comment by neverfox** [comment] 2016-01-23 19:25
Okay, I hope to get to this today.

**Comment by tyleriguchi** [comment] 2016-01-23 20:30
@neverfox I tried a raised button, flat button, text input and they were all throwing that error.

**Comment by neverfox** [comment] 2016-01-23 21:01
I wasn't able to recreate the problem. Here is my [test repo](https://github.com/neverfox/starter-kit-mui-test). You can look at the commits to see the steps I followed. I configured a virtual environment with all of the same version numbers. The only difference is that I'm on El Capitan, though I doubt that would impact anything. Both `npm run deploy` and `NODE_ENV=production npm run deploy` worked without error.

**Comment by tyleriguchi** [comment] 2016-01-23 21:19
@neverfox hey thanks for looking into this, it was because I didn't put it into the compiler vendor. 
```
compiler_vendor : [
     'material-ui',
     'react-tap-event-plugin',
```

**Comment by tyleriguchi** [comment] 2016-01-23 21:31
@neverfox that was an issue as well as some lint errors. Thanks again :+1:

**Comment by neverfox** [comment] 2016-01-23 21:34
@tyleriguchi Great! Glad it's working for you now.

**Comment by davezuko** [comment] 2016-01-24 00:21
:tada: hooray.

**Closed by davezuko** 2016-01-24 00:21 UTC
