### ISSUE TITLE
sinon.useFakeTimers

### ISSUE THREAD

**Issue by CurtisHumphrey** [davezuko/react-redux-starter-kit#835] opened 2016-05-30 19:47 UTC
has anyone tried using FakeTimers from sinon successfully? I keep getting: undefined is not an object (evaluating 'llx.install')

**Comment by davezuko** [comment] 2016-06-14 12:48
Have you tried just using `lolex` independently? https://github.com/sinonjs/lolex.

The issue is with this code in `sinon`:

```js
function makeApi(s, lol) {
        /*global lolex */
        var llx = typeof lolex !== "undefined" ? lolex : lol; // <--------------

        s.useFakeTimers = function () {
            var now;
            var methods = Array.prototype.slice.call(arguments);

            if (typeof methods[0] === "string") {
                now = 0;
            } else {
                now = methods.shift();
            }

            var clock = llx.install(now || 0, methods);
            clock.restore = clock.uninstall;
            return clock;
        };
  // ...
```

So far I haven't found a way to get sinon to properly load `lolex`, no matter how I try to expose it. So, my next best guess would be to just try to use it independently as mentioned in the documentation: 

> For standalone usage of fake timers it is recommended to use lolex package instead. It provides the same set features and was previously extracted from Sinon.JS.

http://sinonjs.org/docs/#clock

**Comment by davezuko** [comment] 2016-06-29 13:07
I'm not sure this is easily fixable on our part, so going to close this by recommending that `lolex` be used independently when this functionality is needed.

**Closed by davezuko** 2016-06-29 13:07 UTC
