### ISSUE TITLE
Problem including 3rd party css when the project is in an src directory

### ISSUE THREAD

**Issue by borlaym** [davezuko/react-redux-starter-kit#514] opened 2016-02-01 12:23 UTC
Hello,

I was struggling with including 3rd party css files from the node_modules directory, it would keep scoping its rules like it does with css in your src directory, obviously breaking the style. The problem was that my whole project was in an src directory, and the webpack config just tests for the string `src` being in the url:

https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L134-L176

It's a pretty fringe case I know, but it did waste me an hour or so.

**Comment by davezuko** [comment] 2016-02-03 22:58
Would adding an exclude on `node_modules` for those loader fix this? My guess is yet, but I don't have anything to test it with right this minute.

**Comment by borlaym** [comment] 2016-02-09 18:50
Steps to reproduce:
- Create a folder called `src`
- Clone the repository inside it
- Install a third party react component that has a css dependency, like fixed-data-table or a datepicker
- Include this component in HomeView.js for example

The styles of the third party component will not appear because they will be namespaced.
You can do it with `node_modules` but I think just making the `src` path relative (`/\.\/src/`) is a better solution.

**Comment by danwad** [comment] 2016-02-21 16:06
@borlaym, did making the `include` parameter of the loader relative (`/\.\/src/`) fix it for you?

I am on Windows so had to change the path separator (`/\.\\src/`) but still this doesn't work as the regex is tested against the absolute path of the file.

I think testing against the `/src/` regex is a bit misleading. When I read the config, I thought intended behaviour was to enable CSS modules for all CSS/SCSS in `./src/` and disable it for all CSS/SCSS outside `./src/` (e.g. `node_modules`), but the broad regex can catch a lot of extra cases.

I have made my config much more explicit:

```
webpackConfig.module.loaders.push({
  test: /\.scss$/,
  include: pathStr => pathStr.startsWith(paths.client()),
  loaders: [
    'style',
    cssLoader,
    'postcss',
    'sass?sourceMap'
  ]
})

webpackConfig.module.loaders.push({
  test: /\.css$/,
  include: pathStr => pathStr.startsWith(paths.client()),
  loaders: [
    'style',
    cssLoader,
    'postcss'
  ]
})

// All other CSS/SCSS is global by default
webpackConfig.module.loaders.push({
  test: /\.scss$/,
  exclude: pathStr => pathStr.startsWith(paths.client()),
  loaders: [
    'style',
    'css?sourceMap&-minimize',
    'postcss',
    'sass?sourceMap'
  ]
})

webpackConfig.module.loaders.push({
  test: /\.css$/,
  exclude: pathStr => pathStr.startsWith(paths.client()),
  loaders: [
    'style',
    'css?sourceMap&-minimize',
    'postcss'
  ]
})
```

**Comment by davezuko** [comment] 2016-02-21 17:23
Should be fixed with https://github.com/davezuko/react-redux-starter-kit/commit/b0b5e7177ecb34032801557ff857e07b10d79da9. Sorry it took so long.

**Closed by davezuko** 2016-02-21 17:23 UTC

**Comment by woniesong92** [comment] 2016-04-13 22:58
@davezuko How would one require a css file in `node_modules`?

Current Location:
`/front/src/views/myView/myView.js`

And I tried
`require('../../node_modules/react-datepicker/dist/react-datepicker.min.css')`
`require('/node_modules/react-datepicker/dist/react-datepicker.min.css')`
