### ISSUE TITLE
lint:fix is broken on latest pull

### ISSUE THREAD

**Issue by mikedevita** [davezuko/react-redux-starter-kit#398] opened 2016-01-05 17:04 UTC
when i run `npm run lint:fix` i get a non zero return code error.. running `eslint . ./ "--fix"` manually gives me the following error..

I am on node v5.1.1

```
/Users/mhdevita/.nvm/versions/node/v5.1.1/lib/node_modules/eslint/lib/config/config-file.js:332
            throw e;
            ^

Error: Cannot read config package: eslint-config-standard-react
Error: Cannot find module 'eslint-config-standard-react'
```

**Comment by SimonSelg** [comment] 2016-01-07 17:45
Works here, and should not happen. Try to delete your node_modules folder and run `npm install` again, maybe something went wrong during the installation. This tends to happen with npm@3 sometimes, unfortunately.

**Comment by davezuko** [comment] 2016-01-07 18:47
I've heard rumors that npm `^3.5.0` helps prevent the missing deps issue, but no real source.

**Comment by davezuko** [comment] 2016-01-11 15:55
Closing since can't repro, will re-open if more details can be provided.

**Closed by davezuko** 2016-01-11 15:55 UTC

**Comment by agoransson** [comment] 2016-02-06 12:12
I'm having same issue now with release 1.0.0.

Here's the debug log.

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/Cellar/node/0.12.2_1/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint:fix' ]
2 info using npm@3.7.1
3 info using node@v5.4.1
4 verbose run-script [ 'prelint:fix', 'lint:fix', 'postlint:fix' ]
5 info lifecycle react-redux-starter-kit@1.0.0~prelint:fix: react-redux-starter-kit@1.0.0
6 silly lifecycle react-redux-starter-kit@1.0.0~prelint:fix: no script for prelint:fix, continuing
7 info lifecycle react-redux-starter-kit@1.0.0~lint:fix: react-redux-starter-kit@1.0.0
8 verbose lifecycle react-redux-starter-kit@1.0.0~lint:fix: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@1.0.0~lint:fix: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/ksango/projects/goodtrade/dist/shop_test/react-redux-starter-kit/node_modules/.bin:/usr/local/Cellar/node/0.12.2_1/bin:/opt/local/bin:/opt/local/sbin:/opt/local/bin:/opt/local/sbin:/usr/local/bin:/usr/local/mysql/bin:/Users/ksango/.rvm/gems/ruby-2.1.0/bin:/Users/ksango/.rvm/gems/ruby-2.1.0@global/bin:/Users/ksango/.rvm/rubies/ruby-2.1.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Users/ksango/sdk/platform-tools:/Users/ksango/sdk/tools:/Users/ksango/Development/gradle-2.2.1/bin:/Users/ksango/.rvm/bin:/Applications/Android Studio.app/sdk/platform-tools:/Applications/Android Studio.app/sdk/tools:/Users/ksango/.composer/vendor/bin
10 verbose lifecycle react-redux-starter-kit@1.0.0~lint:fix: CWD: /Users/ksango/projects/goodtrade/dist/shop_test/react-redux-starter-kit
11 silly lifecycle react-redux-starter-kit@1.0.0~lint:fix: Args: [ '-c', 'npm run lint -- --fix' ]
12 silly lifecycle react-redux-starter-kit@1.0.0~lint:fix: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@1.0.0~lint:fix: Failed to exec lint:fix script
14 verbose stack Error: react-redux-starter-kit@1.0.0 lint:fix: `npm run lint -- --fix`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid react-redux-starter-kit@1.0.0
16 verbose cwd /Users/ksango/projects/goodtrade/dist/shop_test/react-redux-starter-kit
17 error Darwin 14.5.0
18 error argv "/usr/local/Cellar/node/0.12.2_1/bin/node" "/usr/local/bin/npm" "run" "lint:fix"
19 error node v5.4.1
20 error npm  v3.7.1
21 error code ELIFECYCLE
22 error react-redux-starter-kit@1.0.0 lint:fix: `npm run lint -- --fix`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@1.0.0 lint:fix script 'npm run lint -- --fix'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run lint -- --fix
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by kevinchiu** [comment] 2016-02-09 04:56
I am also having this issue when trying to use npm run lint and npm run lint:fix.
```

Error: Cannot read config package: eslint-config-standard-react
Error: Cannot find module 'eslint-config-standard-react'
Referenced from: /Users/kevin/Desktop/trays/.eslintrc
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at loadPackage (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:168:16)
    at loadConfigFile (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:212:18)
    at load (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:385:18)
    at /usr/local/lib/node_modules/eslint/lib/config/config-file.js:326:36
    at Array.reduceRight (native)
    at applyExtends (/usr/local/lib/node_modules/eslint/lib/config/config-file.js:309:28)
```

**Comment by mmermerkaya** [comment] 2016-02-24 22:50
The ELIFECYCLE error is explained here: https://github.com/npm/npm/issues/8802

It is annoying though :)

**Comment by AaronHarris** [comment] 2016-05-11 02:11
The funny thing is this is the opposite of the expected behavior in webpack: if a webpack bundle fails, it still exits with statusCode of 0 by default. Much head banging.
