### ISSUE TITLE
Issues with CSS animations

### ISSUE THREAD

**Issue by zsherman** [davezuko/react-redux-starter-kit#584] opened 2016-02-21 17:31 UTC
Have no idea if this has to do with the project setup (I attempted to rule out everything), but I noticed that keyframe animations don't appear to run when rendered inside components. Has anyone else had this issue or have any thoughts on what might be the cause?

**Comment by zsherman** [comment] 2016-02-21 17:33
As a dead-simple experiment, try rendering this from a component: http://jsfiddle.net/allusis/dQQcX/.

**Comment by davezuko** [comment] 2016-02-21 17:43
Where are you adding these styles? I just edited `HomeView.js`'s Double Async button as follows:

```js
<button className={classes.foo} onClick={this.props.doubleAsync}>
  Double (Async)
</button>
```

And added the following styles to `HomeView.scss`:

```scss
.foo {
  width:100px;
  height:100px;
  background:red;
  position:relative;
  animation:mymove 5s infinite;
}

@keyframes mymove {
  from {top:0px;}
  to {top:200px;}
}
```

And it worked in Chrome, Firefox, and Safari (I don't have access to IE at the moment).

![foo](https://cloud.githubusercontent.com/assets/6439050/13204239/b84ba6ac-d898-11e5-825a-322dd576e59c.gif)

**Comment by zsherman** [comment] 2016-02-21 17:45
So I'm actually importing the styles from a separate partial in `core.scss` – not sure why that'd be different.

**Comment by zsherman** [comment] 2016-02-21 17:51
Potentially related http://stackoverflow.com/questions/31070033/broken-css-keyframe-animations-when-using-webpacks-css-loader-with-uglifyjs-plu.

**Comment by JuoCode** [comment] 2016-03-02 04:04
@zsherman  By default, `cssnano` is enabled with [lots of options](http://cssnano.co/optimisations/); I think your problem may be caused by certain option, and you can disable anyone in `build/webpack.config.js` like below:

```
webpackConfig.postcss = [
  cssnano({
    // ......
  })
];

```

**Comment by macnibblet** [comment] 2016-03-16 12:55
I'm having the exact same reason, the minified css has a differet name for the keyframe and the component uses the "unobfuscated" version. 

![Component](http://caps.interactivesolutions.se/ss/anto/ac6b2d.png)
![CSS File](http://caps.interactivesolutions.se/ss/anto/9d089c.png)

**Comment by macnibblet** [comment] 2016-03-16 12:56
And this is with cssnano completely disabled, so something is renaming the css class in the css file generation but the component className does not get updated.

**Comment by macnibblet** [comment] 2016-03-16 14:31
I have fixed it, but i'm guessing it's just a hack, so a proper solution would be good.
Anyway change this line
https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L173
With
`'localIdentName=[local]'`

**Comment by davezuko** [comment] 2016-03-16 14:33
I feel like this is an issue with CSS modules and not with this project, but I'm not knowledgable enough to know for sure.

**Comment by davezuko** [comment] 2016-03-16 14:36
I feel like this is a limitation of CSS modules, since there literally is nothing out of the ordinary that we're doing with CSS modules. See: https://css-modules.github.io/webpack-demo/

```css
.root {
  padding: 20px 10px;
}

.ball {
  composes: bounce from "shared/styles/animations.css";
  width: 40px;
  height: 40px;
  border-radius: 20px;
  background: rebeccapurple;
}

// share/styles/animations.css
@keyframes bounce {
  33% { transform: translateY(-20px); }
  66% { transform: translateY(0px); }
}

.bounce {
  animation: bounce 1s infinite ease-in-out;
}
```

**Comment by macnibblet** [comment] 2016-03-16 14:39
core.scss
```scss
 @mixin spinner($size: 25px, $spinnerColor: 255, $borderSize: 3px) {
    display: block;
    height: $size;
    width: $size;
    margin: 10px auto;
    animation: rotation .7s infinite linear;
    border-left: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.3);
    border-right: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.3);
    border-bottom: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.3);
    border-top: $borderSize solid rgba($spinnerColor,$spinnerColor,$spinnerColor,.9);
    border-radius:100%;
  }

  .spinner {
    @include spinner(50px, 150, 5px);
  }

  @-webkit-keyframes rotation {
    from {-webkit-transform: rotate(0deg);}
    to {-webkit-transform: rotate(359deg);}
  }

  @-moz-keyframes rotation {
    from {-moz-transform: rotate(0deg);}
    to {-moz-transform: rotate(359deg);}
  }

  @-o-keyframes rotation {
    from {-o-transform: rotate(0deg);}
    to {-o-transform: rotate(359deg);}
  }

  @keyframes rotation {
    from {transform: rotate(0deg);}
    to {transform: rotate(359deg);}
  }

  @mixin clearfix {
    &:after {
      content: "";
      display: table;
      clear: both;
    }
  }

  @import 'spinner-button';
```

spinner-button.scss
```scss
.spinner-button {
  position:relative;
  .spinner-text {
    display: block;
  }
  .spinner-element {
    display: none;

    position: absolute;
    top: 0;
    left: 0;
    border-radius: 5px;
    width: 100%;
    height: 100%;

    span {
      @include spinner;
    }
  }
  &.show {
    .spinner-text {
      color: transparent;
    }
    .spinner-element {
      display: block;
    }
  }
}
```

I'm guessing i'm doing something wrong and should be import my scss into react somehow according to https://github.com/css-modules/css-modules#css-modules ?

**Comment by davezuko** [comment] 2016-03-16 14:43
You have to either use `compose` or declare these as `:global` styles.

See: https://github.com/webpack/css-loader/issues/65 and https://github.com/webpack/css-loader/issues/243 (and a few other assorted issues).

I'm going to close this since it is not an issue with this starter kit but more a misunderstanding of CSS modules (I'm new to it myself, so it's been hard to troubleshoot). If you find yourself fighting with the modules more often than not, I'd consider disabling them in favor of good ol' fashioned sass. Feel free to keep discussing it here, but I don't see any evidence that this behavior is a result of this project.

**Comment by macnibblet** [comment] 2016-03-16 14:45
@davezuko Now that we figured out how you are supposed to use it properly I find it kinda awesome, really allows from small components!

**Comment by zsherman** [comment] 2016-03-16 14:48
@davezuko fwiw I believe this was a file nested inside of the `:global` scope.

**Comment by davezuko** [comment] 2016-03-16 14:50
@zsherman well, that changes things... I'm still hesitant to chalk it up to this project, but again based on my inexperience with this I could be totally wrong. Seeing as I'm not much help here, I'd suggest reposting this to css-modules or css-loader and see if they can offer any help. If it does end up being a problem specific to this project then I will definitely re-open, but I've been fiddling with this for a while without any real progress.

Maybe I'll give this a spin using `.css` rather than `.scss` and see if that yields anything different.

**Comment by zsherman** [comment] 2016-03-16 14:53
Yeah I wouldn't say it's the highest priority issue, but it's a little strange that certain styles work in the global scope, and animations do not – I still suspect a cssnano issue.

**Comment by davezuko** [comment] 2016-03-16 14:56
Re-opening to try to apply fixes from the issue you referenced: http://stackoverflow.com/questions/31070033/broken-css-keyframe-animations-when-using-webpacks-css-loader-with-uglifyjs-plu

**Comment by davezuko** [comment] 2016-03-17 04:11
Recommendations were slightly outdated, but made similar updates here: https://github.com/davezuko/react-redux-starter-kit/pull/656. If issues still persist I'd follow my above recommendation and post in css-loader or css-modules to get a better idea as to whether it's an issue with our configuration (not unlikely) or not.

**Closed by davezuko** 2016-03-17 04:11 UTC
Labels: Needs Investigation

**Comment by ACregan** [comment] 2016-04-05 22:20
Ive moved my transitions from the modules to a animations.scss file imported from the _base.scss file and all is well, you can even use ReactCSSTransitionGroup without any problems.

**Comment by tseho** [comment] 2016-05-31 11:51
@ACregan do you still have the ReactCSSTransitionGroup working with the latest version ?

**Comment by ACregan** [comment] 2016-05-31 14:12
I have not upgraded it for the project I was using that with. I know there
have been some changes as I was using it for a different project and
noticed a lot of differences in the scaffolding. I can try it this evening
if you need me to?


Regards,

Anthony Cregan

*AnthonyCregan.co.uk <http://www.anthonycregan.co.uk/>*
*t:* 07885 757 322
*e: *Tony@TDCbitworks.co.uk <tony@tdcbitworks.co.uk>

**Comment by tseho** [comment] 2016-05-31 17:09
@ACregan Thanks for the response but I finally had it working, I was blaming react-redux-starter-kit for no good reason.

**Comment by nickgnd** [comment] 2016-07-07 22:39
I had the same problems (animation not working) with [loaders.css](https://github.com/ConnorAtherton/loaders.css) library, it seems it lost the `@key-frames` for the animation after `postcss` build. I tried to work with `postcss` config and plugins to fix the error, but I've not been able to make it work.

I solved putting the library between the compiler vendor libraries in `confgi/index.js`

```
  // ----------------------------------
  // Compiler Configuration
  // ----------------------------------
  compiler_css_modules     : true,
  compiler_devtool         : 'source-map',
  compiler_hash_type       : 'hash',
  compiler_fail_on_warning : false,
  compiler_quiet           : false,
  compiler_public_path     : '/',
  compiler_stats           : {
    chunks : false,
    chunkModules : false,
    colors : true
  },
  compiler_vendor : [
    'history',
    'react',
    'react-redux',
    'react-router',
    'react-router-redux',
    'redux',
    'loaders.css' // add here <-----
  ]
```
