### ISSUE TITLE
QUESTION: after compiler, product is blank on some version iPhone mobile bowser

### ISSUE THREAD

**Issue by zedde** [davezuko/react-redux-starter-kit#911] opened 2016-07-07 03:31 UTC
```javascript
npm run deploy:prod
npm run start:prod
```
start:prod is
```javascript
  "scripts": {
    "clean": "rimraf dist",
    "compile": "better-npm-run compile",
    "lint": "eslint src tests server",
    "lint:fix": "npm run lint -- --fix",
    "deploy": "better-npm-run deploy",
    "deploy:dev": "better-npm-run deploy:dev",
    "deploy:prod": "better-npm-run deploy:prod",
    "start": "better-npm-run start",
    "start:prod": "better-npm-run start:prod"
  },
  "betterScripts": {
    "start:prod": {
      "command": "babel-node bin/server",
      "env": {
        "NODE_ENV": "production",
        "DEBUG": "app:*"
      }
    }
  }
```
Open http://myip:3000 in iPhone Safari `"Mozilla/5.0 (iPhone; CPU iPhone OS 9_3_2 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13F69 Safari/601.1"` is work

But  Safari `Mozilla/5.0 (iPhone; CPU iPhone OS 8_0_2 like Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12A405 Safari/600.1.4`. it didn’t working.

also in development mode, both working.

I would appreciate if you could help me out :-)

**Comment by zedde** [comment] 2016-07-07 03:32
Some versions of android like so ...

**Comment by nie-xin** [comment] 2016-07-07 07:47
Might caused by react-optimize on production, can you try to remove it from  build/webpack.config.js and test again?  

```
    env: {
      production: {
        presets: ['react-optimize']    // remove this
      }
    }
```

**Comment by zedde** [comment] 2016-07-07 12:17
@nie-xin  👍  
thank you~ 
by the way, i also find other bug... :0

**Comment by davezuko** [comment] 2016-07-07 13:37
Closing as duplicate.

**Closed by davezuko** 2016-07-07 13:37 UTC
