### ISSUE TITLE
compiled and when run in apache loads but nothing rendes

### ISSUE THREAD

**Issue by psound** [davezuko/react-redux-starter-kit#1178] opened 2017-02-28 18:21 UTC
I am trying to render the static files of the dist folder, I see all rendering correctly on my log. No errors but nothing displays on the page. I am running a simple apache server. Please help

Thanks
-Pedro

**Comment by razazaidisd** [comment] 2017-03-01 08:19
When you open in browser is it taking the right URL? I think you need to change to 'localhost' in config/project.config.js line 26 .

**Comment by alex-bu-89** [comment] 2017-03-18 14:54
Maybe the problem is routing and history http://stackoverflow.com/a/37557805.
Look at `history` in `AppContainer`.  `hashHistory` works for me.

**Comment by davezuko** [comment] 2017-04-04 13:20
Is this from a fresh clone of this project? If not, please link to your source (or website, even, if you can). Closing in the meantime.

**Closed by davezuko** 2017-04-04 13:20 UTC
