### ISSUE TITLE
Compile and deploy fails

### ISSUE THREAD

**Issue by fredrik-sogaard** [davezuko/react-redux-starter-kit#640] opened 2016-03-12 14:45 UTC
`npm run deploy` and `NODE_ENV=production npm run compile` fails.

I get this in Terminal right before npm errors output:
` app:bin:compile Compiler encountered an error. +1ms [Error: Webpack compiler encountered errors]`

Node version: `5.2.0`
Npm version: `3.6.0`

npm-debug.log here:
```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/fredrik/.nvm/versions/node/v5.2.0/bin/node',
1 verbose cli   '/Users/fredrik/.nvm/versions/node/v5.2.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy' ]
2 info using npm@3.6.0
3 info using node@v5.2.0
4 verbose run-script [ 'predeploy', 'deploy', 'postdeploy' ]
5 info lifecycle react-redux-starter-kit@1.0.0~predeploy: react-redux-starter-kit@1.0.0
6 silly lifecycle react-redux-starter-kit@1.0.0~predeploy: no script for predeploy, continuing
7 info lifecycle react-redux-starter-kit@1.0.0~deploy: react-redux-starter-kit@1.0.0
8 verbose lifecycle react-redux-starter-kit@1.0.0~deploy: unsafe-perm in lifecycle true
9 verbose lifecycle react-redux-starter-kit@1.0.0~deploy: PATH: /Users/fredrik/.nvm/versions/node/v5.2.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/fredrik/Websider/react-redux-starter-kit/node_modules/.bin:/usr/local/heroku/bin:/Users/fredrik/.rvm/gems/ruby-2.0.0-p247/bin:/Users/fredrik/.rvm/gems/ruby-2.0.0-p247@global/bin:/Users/fredrik/.rvm/rubies/ruby-2.0.0-p247/bin:/Users/fredrik/.rvm/bin:/Users/fredrik/.nvm/versions/node/v5.2.0/bin:/Users/fredrik/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/fredrik/Documents/AWS-ElasticBeanstalk-CLI-2.5.1/eb/macosx/python2.7:/Users/fredrik/.composer/vendor/bin:/Users/fredrik/Documents/android-sdk-macosx/tools:
10 verbose lifecycle react-redux-starter-kit@1.0.0~deploy: CWD: /Users/fredrik/Websider/react-redux-starter-kit
11 silly lifecycle react-redux-starter-kit@1.0.0~deploy: Args: [ '-c', 'better-npm-run deploy' ]
12 silly lifecycle react-redux-starter-kit@1.0.0~deploy: Returned: code: 1  signal: null
13 info lifecycle react-redux-starter-kit@1.0.0~deploy: Failed to exec deploy script
14 verbose stack Error: react-redux-starter-kit@1.0.0 deploy: `better-npm-run deploy`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/Users/fredrik/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at EventEmitter.emit (events.js:173:7)
14 verbose stack     at ChildProcess.<anonymous> (/Users/fredrik/.nvm/versions/node/v5.2.0/lib/node_modules/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:88:13)
14 verbose stack     at ChildProcess.emit (events.js:173:7)
14 verbose stack     at maybeClose (internal/child_process.js:819:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:212:5)
15 verbose pkgid react-redux-starter-kit@1.0.0
16 verbose cwd /Users/fredrik/Websider/react-redux-starter-kit
17 error Darwin 15.3.0
18 error argv "/Users/fredrik/.nvm/versions/node/v5.2.0/bin/node" "/Users/fredrik/.nvm/versions/node/v5.2.0/bin/npm" "run" "deploy"
19 error node v5.2.0
20 error npm  v3.6.0
21 error code ELIFECYCLE
22 error react-redux-starter-kit@1.0.0 deploy: `better-npm-run deploy`
22 error Exit status 1
23 error Failed at the react-redux-starter-kit@1.0.0 deploy script 'better-npm-run deploy'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the react-redux-starter-kit package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     better-npm-run deploy
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs react-redux-starter-kit
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls react-redux-starter-kit
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by davezuko** [comment] 2016-03-13 20:32
May be related to https://github.com/davezuko/react-redux-starter-kit/issues/571, so check that out and see if that fixes your issue. I just got back on vacation and will try to fix some of these issues this week.

**Comment by davezuko** [comment] 2016-03-16 20:47
Closing since I believe this has been solved with the issue referenced above. If that issue did not solve your problem let me know and I can investigate further, but I believe this to be related to heroku's not installing dev dependencies.

**Comment by fredrik-sogaard** [comment] 2016-03-18 08:56
@davezuko I looked through that issue, but it didn't really help. And to be clear: I'm not doing anything on/with Heroku? I'm just trying to compile locally.

**Comment by davezuko** [comment] 2016-03-18 14:28
@fredrik-sogaard I will read through it again, sorry. I glanced at the log and saw heroku somewhere in there so just assumed... re-opening.

That said, can you confirm this still happens after a fresh npm install of the latest version of the starter kit?

**Comment by fredrik-sogaard** [comment] 2016-03-20 07:19
@davezuko A fresh clone of the latest starter kit version works. I have two questions:
1. Will lint errors make the compile fail in the way I see above?
2. What's the best strategy to keep my repo updated with the starter kit?

**Comment by davezuko** [comment] 2016-03-20 13:46
@fredrik-sogaard lint errors should fail it, but you should see them in the console output which would indicate why it failed. Just for posterity, I personally setup linting differently in non-dev environments, where `npm run lint` is run first before webpack, and then webpack runs w/o the eslint loader. This is mostly just so builds will fail faster if a lint error exists, since webpack doesn't have to process the entire codebase first.

As far as #2, unfortunately there isn't a super great way right now, aside from pulling from remote and fixing merge conflicts as they arise (it's very rare that I push non-build-related code anymore). I've mentioned in the past that our team built a tool to keep our applications in sync from this repo, but it's unfortunately not yet open sourced. I realize this workflow is a bit cumbersome, so I'll try to push for getting some of our utilities released.

**Comment by davezuko** [comment] 2016-03-20 15:47
Closing since it's confirmed to be fixed (my guess is that it stems from the old ESLint issue, but I can't be certain). We can still continue the discussion, though.

**Closed by davezuko** 2016-03-20 15:47 UTC
Labels: Needs Investigation
