### ISSUE TITLE
Make this starter kit universal

### ISSUE THREAD

**Issue by kai23** [davezuko/react-redux-starter-kit#212] opened 2015-12-02 16:13 UTC
Hi !

It's not really an issue, but more a question about universal javascript.

I'm trying to make this starter kit universal, but I don't get all.

I've followed [this tutorial](http://redux.js.org/docs/recipes/ServerRendering.html) from the redux tutorial, but still, I don't get all.

Do you have any tutorial or project which could help me ? Or any clue to make it universal ?

I really love what you are doing with this starter kit, and really want to use it for a huge project, but our C.T.O doesn't want me to forget the "universal javascript hype", at least for SEO.

We used to use Fluxible for others projects, but we also want to move on to redux.

Thanks in advance if you have anything for me

**Comment by mtsr** [comment] 2015-12-02 16:21
I guess even this doesn't become part of the starter kit (which is a good thing IMO), it would still be good to give the users some pointers.

**Comment by davezuko** [comment] 2015-12-02 16:25
It would be a good idea to add some documentation around this (especially considering the fact that it _used_ to be a universal kit). Until I can get to this, there are two things that you could check out directly related to this kit:

1) https://github.com/davezuko/me - specifically everything in https://github.com/davezuko/me/tree/master/lib which is used in https://github.com/davezuko/me/blob/master/build/deploy.js. It's nowhere close to being finished, but I use it to bake static files for each of the routes (hardcoded at the moment), which is very similar to what is done for sever-side rendering.

2) https://github.com/davezuko/react-redux-starter-kit/tree/v0.14.0 This starter kit used to be isomorphic, though only on a very rudimentary level (no dynamic data pre-fetching, though it wouldn't be hard). I know digging through source code isn't the easiest thing, but the server setup here is much simpler than the example above.

**Comment by kai23** [comment] 2015-12-02 16:27
Thank you for the links.

Can I ask why you removed the isomorphic render from the starter kit ?

**Comment by davezuko** [comment] 2015-12-02 16:30
Kinda along the lines of what @mtsr said, it just adds a lot more complexity to the starter kit to the point where it gets too confusing. I wanted to build something that is easy to get up and running quickly, but is extensible and easy to build on top of, not a full solution from the outset.

**Comment by kai23** [comment] 2015-12-02 16:33
Well, I agree that it's the simplicity of this started kit that made me really like it.

Although, I can't find any starter kit between yours, and the one from [erikras](https://github.com/erikras/react-redux-universal-hot-example) which is, for me, really too big. I just want something just easy as yours, but with an understandable universal javascript :)

**Comment by davezuko** [comment] 2015-12-02 17:14
I totally understand, it's just such a hard thing to balance. Hopefully we can get some documentation in place to make the process a bit easier to understand.

**Comment by davezuko** [comment] 2015-12-05 19:53
Closing this for now, I'll try to get some documentation incorporated to point people in the right direction, but this will never be a huge focus for the kit.

**Closed by davezuko** 2015-12-05 19:53 UTC
Labels: question

**Comment by mtsr** [comment] 2015-12-05 19:55
I guess I have one comment here. Maybe somebody can give some pointers what one needs to do or avoid to keep it possible to add universal rendering to their app at some future point in time.

**Comment by davezuko** [comment] 2015-12-05 20:06
@mtsr good point, and I have plans to -- mostly likely in https://github.com/davezuko/react-redux-starter-kit/issues/221 or something similar.

**Comment by sars** [comment] 2015-12-16 08:59
@davezuko , I understand your point about keeping this repository as simple as possible, but on the other hand, SSR is something, that brings important advantages. And I don't see disadvantages so far, please point me, if there are.
If we would find simple solution for SSR, that wouldn't complicate code to much - it would be awesome.

**Comment by davezuko** [comment] 2015-12-16 13:17
@sars, I agree SSR is not that difficult, but being part of the kit presents a few issues -- which were the cause of its prior removal. By including it, we're saying "we support this"; anything lesser (oh, we're only implementing naive view rendering) and we might as well not do it. With that, here's what we ran into before:

* Folder aliases (Now resolve.root). This can't be used if we're importing the app from the server, so they'd either have to be dropped or the server would have to be compiled with webpack. No big loss, but a loss nonetheless.
* Style imports are now complicated. With global styles (pre-CSS modules) it didn't matter much since the classnames were hardcoded on the elements. Now, with CSS modules, those classnames are generated by webpack. I'm not sure how this could be solved without bundling the server.

**Comment by janoist1** [comment] 2016-07-25 15:46
If anyone is still looking for a universal version of this great starter kit, check out my [forked version](https://github.com/janoist1/react-redux-starter-kit/tree/feature/universal). This is fresh, needs to be tested, but shows the base concept.

**Comment by janoist1** [comment] 2016-07-26 09:26
Done. Also, I fixed the eslint errors.
