### ISSUE TITLE
Getting error on npm run deploy:prod, after porting code from previous version of this library.

### ISSUE THREAD

**Issue by abhinavzspace** [davezuko/react-redux-starter-kit#1101] opened 2016-12-09 12:40 UTC
I tried porting a previous project built on top of this library's 3 months old version to current version.

I am getting the following error on running `npm run deploy:prod`. `deploy`, `deploy:dev` and `npm start` are working fine.

There might be something wrong in my code. Please close this, if that is the most likely reason.

BTW fantastic light weight library. :)

```
app:bin:compile Webpack compiler encountered errors. +20ms
  app:bin:compile 0.home.ea5ec349f2e946ae67e6.js from UglifyJs
SyntaxError: Unexpected token: name (name) [./~/w3c-keyname/index.js:104,0] +1ms
  app:bin:compile Compiler encountered an error. Error: Webpack compiler encountered errors
    at compiler.run (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/bin/compile.js:25:23)
    at Compiler.<anonymous> (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/webpack/lib/Compiler.js:194:14)
    at Compiler.emitRecords (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/webpack/lib/Compiler.js:282:37)
    at Compiler.<anonymous> (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/webpack/lib/Compiler.js:187:11)
    at /Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/webpack/lib/Compiler.js:275:11
    at Compiler.applyPluginsAsync (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/tapable/lib/Tapable.js:60:69)
    at Compiler.afterEmit (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/webpack/lib/Compiler.js:272:8)
    at Compiler.<anonymous> (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/webpack/lib/Compiler.js:267:14)
    at /Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/async/lib/async.js:52:16
    at done (/Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/async/lib/async.js:246:17)
    at /Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/async/lib/async.js:44:16
    at /Users/abhinav/projects/docri-temp/react-redux-starter-kit/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:123:15) +0ms
```

**Comment by davezuko** [comment] 2016-12-09 14:29
Could you please link to your source? This is not something I can reproduce in the base starter kit because it does not include whatever code modifications you have made.

**Comment by abhinavzspace** [comment] 2016-12-10 05:52
[This](https://bitbucket.org/abhinavzspace/docri-web/overview) is the source. For now I have commented uglifyjs from config/webpack.config.js. And I have also removed `npm run lint && npm run test` from deploy command in npm. I have not written any tests. :(

I can't thank you enough for looking into code. 👍

**Comment by abhinavzspace** [comment] 2016-12-20 18:47
Any luck with this? If you can give me some direction, even that will do.

**Comment by davezuko** [comment] 2016-12-27 06:18
I have looked and unfortunately did not see anything obvious; perhaps I can revisit it after the holidays!

**Comment by abhinavzspace** [comment] 2016-12-28 04:26
Sure.. thanks.

**Comment by bytewiz** [comment] 2017-01-08 22:41
@davezuko any news on this, also happens to me when running `npm run deploy:prod`

**Comment by bytewiz** [comment] 2017-01-08 22:53
@davezuko @abhinavzspace I don't know if you run tests but for me it was the `npm test` that crashed the build. I for now just turned off `npm test` and now it works running `npm run deploy:prod`

**Comment by davezuko** [comment] 2017-01-08 22:56
@bytewiz I do run tests and they do run on CI for each commit to this project. I really have no idea what it could be as I can't reproduce on my machine, though that's not to say there isn't an issue for others.

**Comment by bytewiz** [comment] 2017-01-09 21:48
@davezuko Oh my tests runs now my bad, I have a weird typo err. so not a problem for me anymore 👍

**Comment by davezuko** [comment] 2017-05-18 00:23
Closing since the project has been completely overhauled: https://github.com/davezuko/react-redux-starter-kit/releases/tag/v3.0.0.

**Closed by davezuko** 2017-05-18 00:23 UTC
