### ISSUE TITLE
FlowType Integration/Not Working

### ISSUE THREAD

**Issue by saem** [davezuko/react-redux-starter-kit#192] opened 2015-11-24 06:54 UTC
This is a question, but seeing as there are a few of those in the issue tracker I thought it was ok to ask. Thanks for putting this boilerplate together, it's awesome.

Preamble
-------------
I'm trying to get FlowType annotations working within my project, I've taken the boilerplate, and done a fair bit at this point. Specifically, using react-bootstrap, ditching redux and switching to freezer, and so on. Everything, was going swimmingly, until I tried to use FlowType.

What I've Tried
--------------------
Getting FlowType integrated hasn't worked (this is more than likely my lack of webpack experience), at this point, I'll just run the separate python server. Integration would be nicer, of course. I've tried getting this to work by putting in [Dan's flow loader](https://github.com/gaearon/flowcheck-loader) at the beginning of the module.loaders in the config (`build/webpack/development.js`), but it doesn't seem to work. I ignored the jsx stuff (striptypes and harmony), because babel doesn't seem to mind type annotations.

Error I Get
--------------
At first things seem to work fine, so I added an annotation, but as soon as I remove it, I get `Uncaught TypeError: Cannot read property 'apply' of undefined`. Even if I undo all changes, and reload I continually get the same error. I have to kill the webpack server, and restart it. This is thrown on line 23 of what looks like the JSONP callback for chunk loading (I think [this](https://github.com/webpack/webpack/blob/72e8dd01475841b5123607efd8b3c7b892c1a32a/lib/JsonpMainTemplatePlugin.js#L107) might be the code).

Why I don't have a Test Case
---------------------------------------
I tried replicating this by pulling down the latest boilerplate, but I'm finding that hot reloading isn't working at all for me. I'm guessing it's a similar situation to [this ticket](https://github.com/davezuko/react-redux-starter-kit/issues/188).

Thanks!

**Comment by davezuko** [comment] 2015-11-24 14:38
Hey I'll take a look at this as soon as I get a chance. Have you by chance tried to use [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck)? Just curious because I never really managed to get a great Flow setup with webpack (ended up just running the flow check process separately) and haven't had a chance to try the babel plugin yet. I'll take a look at both either way.

**Comment by saem** [comment] 2015-11-24 21:41
@davezuko thanks for the prompt reply, sorry I'm being slow. Yeah, I tried that, and it even worked, in so far as no complaints from the build system. But there is a large gap, it only looks at the annotations, so I started creating interfaces/declarations for RxJS and react-bootstrap, but babel-plugin-typecheck doesn't use those at all. it just does basic flow-esque checks. It's not nearly as capable from what I've seen.

Looking through the [main source file](https://github.com/codemix/babel-plugin-typecheck/blob/master/src/index.js) seems to confirm that they're just implementing a subset, rather than reusing the work in flowtype.

**Comment by davezuko** [comment] 2015-11-26 13:56
Ok, thanks for the explanation. I'm gone until Sunday on vacation, but I'll keep looking into this when I get back. Sorry for the delay.

**Comment by davezuko** [comment] 2015-12-01 15:02
@saem finally have some time to take a look at this, have you had any progress in the meantime? I'll see what I can uncover.

**Comment by saem** [comment] 2015-12-01 16:47
So sorry @davezuko I should have reported my progress sooner -- I hope the vacation treated you well.

So here is where I got, so rewinding there are two problems the first one is just a roadblock and that's HMR breaking with the error mentioned above. I've summarized it below, but the gory details in long winding sentence form follows after

Summary:
* HMR was breaking on a part of lodash (dependency of react-bootstrap at least)
* Had to setup HMR accept and dispose callbacks as the react-transform-hmr isn't magic
* Updated various dev packages (try anything debugging)
* dedupeplugin, breaks HMR, when using flowtype annotations
* Currently can run flow in the background
* I'm going to give Dan's plugin a try now that I understand webpack better, I think it'll be easier to load

_HMR Breakage_

I started by debugging the webpack HMR code a bunch, and learned about the file that webpack brings in, and learned to read it and follow the __webpack_require__ calls to see how dependencies were working out. I eventually discovered that it was breaking on some lodash piece, which is required by react-bootstrap (at least).

I assumed because I've done some fairly extensive surgery to the framework, I had to introduce some HMR handling of my own you can find the code [here](https://github.com/saem/hairpiece/blob/master/frontend/src/app.js). That particular file is the entry point and you just work up. I have changed things around a fair bit, so if you have questions feel free to ask (I can answer them here or else where if you prefer). Fair warning, it's really raw, as I'm mostly trying to tackle the unknowns than focus on the product.

During this whole bit I updated a number of dependencies, no major versions, but bumped wherever I could (babel, webpack plugins, etc...).

_Flow Type_

After HMR was in a good state, began working on flowtype. I figured something like lodash was used by more than react-bootstrap, and usually this stuff is isolated, but I knew a dedupe plugin existed. I also know that it has, at least in the past, been reported to break HMR (can't remember where I saw that). I decided to disable it. Restarted the dev server, and lo-and-behold it all works. =D

Next I'm going to try Dan's plugin, I think I have a better understanding of webpack, so I think I know how to integrate it.

**Comment by davezuko** [comment] 2015-12-02 17:24
Wow I can't believe you went through all of that, impressive. So the crux of the problem is the dedupe plugin if I'm understanding you correctly?

I apologize for the terseness of my reply in comparison to your incredibly detailed explanations, but I'm so far behind where you are that I don't have much to add just yet. All of this work is incredibly interesting and appreciated, however.

**Comment by saem** [comment] 2015-12-02 19:14
Yup, the dedupe plugin is causing sadness. I haven't had a chance to really dig into what going wrong there, I'll have a look at it soon -- currently engrossed in freezer/rxjs, and learning elm.

For those in my situation where they're using this as a starting point and making a radical departure from redux, like myself, I think maybe a comment by the dedupe plugin might be enough?

I really appreciate all you've done for me by just putting this whole starter kit together, it's fantastic, I just think this is minimum I can do to pay you back. =)

**Comment by davezuko** [comment] 2015-12-05 19:55
@saem I'll definitely figure out some way to document everything you've figured out so people can use this as a reference. I'll close this for now but might create a global "resources" issue for common questions/problems and then link to this from there.

Thanks again for all your work.

**Closed by davezuko** 2015-12-05 19:55 UTC
Labels: question

**Comment by amilajack** [comment] 2016-10-11 16:35
It's been a while since this was closed and Flowtype has matured a lot. Integration is much easier now. I'm working on an ESLint plugin that runs flow as an ESLint plugin:

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

Thoughts?
