### ISSUE TITLE
How to enable sourcemaps

### ISSUE THREAD

**Issue by shredding** [davezuko/react-redux-starter-kit#892] opened 2016-06-28 15:10 UTC
I'm new to the package and really like it, but I have one major problem: Whenever an error occurs in my code it says

```
Uncaught Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.
```

... in the console log with a link to the compiled javascript, somewhere where it has nothing to do with my code, leaving me guessing where the problem is.

How do I enable sourcemaps in chrome and make the error actually show where something goes wrong?

I'm able to set breakpoints in the source code (non compiled), so that is not the problem. The problem is that the actual error is not displayed in the console but this weird error above.

**Comment by davezuko** [comment] 2016-06-29 12:57
Duplicate of: https://github.com/davezuko/react-redux-starter-kit/issues/888. We're still working on this, so no answer for you just yet.

**Closed by davezuko** 2016-06-29 12:57 UTC

**Comment by shredding** [comment] 2016-06-29 13:14
Okay, didn't see that. Thanks.

**Comment by stupidisum** [comment] 2016-07-07 09:14
I checked docs of [redbox](https://www.npmjs.com/package/redbox-react) you are using and found a s
olution.

in `config/index.js`
```
compiler_devtool         : 'eval',
```
And I think swallowing error in console is bad even if you have redbox, so add `throw error` in `src/main.js`
```
      catch (error) {
        renderError(error);
        throw error;
      }
```
