### ISSUE TITLE
__karmaWebpackManifest__ can have files in it on the first run

### ISSUE THREAD

**Issue by CurtisHumphrey** [davezuko/react-redux-starter-kit#624] opened 2016-03-02 23:35 UTC
I'm not quite sure how but __karmaWebpackManifest__ on the first run (no watch) can have files in it and that messes with the local code coverage results.  I'm not sure how to fix it either.

**Comment by davezuko** [comment] 2016-03-17 03:59
Hey thanks for the report @CurtisHumphrey. I'm a bit lost as to what led you to discover this or how to reproduce/see the issue. Could you provide a few more details? Thanks.

**Comment by davezuko** [comment] 2016-03-31 18:50
Have played with this further and am still unable to reproduce. Closing until there are steps to reproduce; super interested in this though, so would love to hear more.

**Closed by davezuko** 2016-03-31 18:50 UTC
Labels: Needs Investigation
