### ISSUE TITLE
What to change to host the app under /app URL?

### ISSUE THREAD

**Issue by sanfilippopablo** [davezuko/react-redux-starter-kit#807] opened 2016-05-13 22:40 UTC
I want to serve the app under /app. I changed compiler_public_path in `_base.js` and `_development.js` but the dev server still gives _Not Found_ on the route.

**Comment by bytewiz** [comment] 2016-05-14 15:44
won't it work if you just change the index path to "/app" or is that not what you want?

**Comment by sanfilippopablo** [comment] 2016-05-16 13:26
I want the `index.html` of the app to be also served in /app/index.html. That way, I can serve it with the same webserver that serves a website in /index.html. Everything would have to be under /app. It's working with the generated dist, but it's not with the development server.

**Comment by mouhsinelonly** [comment] 2016-06-02 14:23
i faced the same problem routes do not work under sub folder

**Comment by sanfilippopablo** [comment] 2016-06-02 14:30
@mouhsinelonly I solved it. I forgot to post it here. When I have the time in a few hours I'll post here. Maybe do a PR too.

**Comment by bytewiz** [comment] 2016-06-02 14:31
@sanfilippopablo sounds good actually need this aswell 👍

**Comment by sanfilippopablo** [comment] 2016-06-02 22:22
OK, the PR will have to wait, because I can't get HMR to work with this setup, but this is what I did:
- Change `compiler_public_path` to _/app/_.
- Set the option `index: '/app/index.html'` in the historyApiFallback middleware config options.
- Use koa-mount to mount the static serving middleware: `app.use(convert(mount('/app', serve(paths.client('static')))))`
- And, of course, change the path of the root route to _/app_.

I'd like to make it work with HMR and make a pull request but I don't really have the time right now. Maybe I can do it over the weekend, but anyone with the time feel free to do it.

**Comment by tiborkr** [comment] 2016-07-05 15:44
@sanfilippopablo Did you have any luck figuring out HMR?

**Comment by sanfilippopablo** [comment] 2016-08-03 20:51
@tiborkr No, sorry buddy. I have only one project which uses this and I'm without HMR on it.

**Comment by nhagen** [comment] 2016-09-27 19:34
I think I had this issue and got it working. The problem is that the HMR server is not configured to listen on the right path. In `server/main.js`:

    app.use(webpackDevMiddleware(compiler, publicPath));
    app.use(webpackHMRMiddleware(compiler, { path: `${ publicPath }/__webpack_hmr` }));

In `webpack.config.json`

```
  app: __DEV__
    ? [APP_ENTRY_PATH, `webpack-hot-middleware/client?path=${ config.compiler_public_path }/__webpack_hmr`]
    : [APP_ENTRY_PATH],
```

The additional argument to `webpackHMRMiddleware` is what I was missing.

**Comment by davezuko** [comment] 2016-12-27 06:26
@nhagen's fix has been merged into master :)

**Closed by davezuko** 2016-12-27 06:26 UTC
