### ISSUE TITLE
`better-npm-run` overrides `env` variables

### ISSUE THREAD

**Issue by amangeot** [davezuko/react-redux-starter-kit#690] opened 2016-04-02 21:07 UTC
Hello David,
I just pulled your last commits. It shows two new commands: `deploy:dev` and `deploy:prod` which both call `deploy`.

I ran some tests on my machin (Windows) and it appears that `better-npm-run` takes the `env` variable from the last script called. So `deploy` will override variables from `deploy:dev`.

For example, here `dev:lan` will run the server at 127.22.203.56:5050:

```
"dev": {
      "command": "nodemon --exec babel-node bin/server",
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*",
        "PORT": 5050
      }
},
"dev:lan": {
      "command": "npm run dev",
      "env": {
        "PORT": 2020,
        "HOST": "172.22.203.56"
      }
},
```

Thank you again for all the work you put into this starter kit!

**Comment by davezuko** [comment] 2016-04-02 21:48
Hey @amangeot, could you clarify something please: does it override the _entire_ variable, or just the environment variables that are duplicated? With `npm run deploy`, what we're expecting is:

`DEBUG` should be set to `app:*` from the `deploy` script. Then, `deploy:prod` would _add_ the environment variable `NODE_ENV` to this, setting it as `production` (and similarly "development" for `deploy:dev`). This should mean that when the deploy script finally runs, the two are merged and, taking `deploy:prod` as an example, the environment variables are:

```
DEBUG: app:*
NODE_ENV: production
```

Based on your example and the expected behavior of the deploy scripts, I don't see the issue with the current setup in the context of the starter kit.

That said, given your example, I do see how it causes issues in your scenario. Given your setup and expected result, I'd almost recommend filing an issue with `better-npm-run` directly, but I think there are tradeoffs whichever way the variables are applied. What about making a generic/internal dev script that both `dev` and `dev:lan` call, to circument the issue?

```
"_dev": {
      "command": "nodemon --exec babel-node bin/server",
},
"dev": {
      "command": "better-npm-run _dev",
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*",
        "PORT": 5050
      }
},
"dev:lan": {
      "command": "better-npm-run _dev",
      "env": {
        "PORT": 2020,
        "HOST": "172.22.203.56"
      }
},
```

**Comment by amangeot** [comment] 2016-04-03 16:13
Sorry I was not clear about it. This creates no problem on my side by the way. I filed this issue because I believe `deploy:dev` ends up with `NODE_ENV` being `production` instead of `development` as you would expect ?

`better-npm-run` overrides individual environment variables that are duplicated. For instance, `dev:lan` has its `HOST` variable left untouched, but calling `dev` replaces its `PORT` variable (ending up with `5050`) in our example.

I actually like the way it works, it allows us to do stuff like this:

```
    "dev": {
      "command": "nodemon --exec babel-node bin/server",
      "env": {
        "NODE_ENV": "development",
        "DEBUG": "app:*",
        "PORT": 5050
      }
    },
    "dev:lan": {
      "command": "npm run dev",
      "env": {
        "HOST": "172.22.203.56"
      }
    },
```

**Comment by davezuko** [comment] 2016-04-03 16:26
So this confirms my suspicion that the diff for the PR wasn't super clear due to github trying to be smart about the diff. If you look at [this commit](https://github.com/davezuko/react-redux-starter-kit/commit/5144048fe0486ebdb33000bdf150a83b073304df#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L42), we removed `NODE_ENV` from the base `deploy` script to prevent the exact issue you're referring to. This is undoubtedly unclear if you just look at the [PR diff](https://github.com/davezuko/react-redux-starter-kit/pull/689/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R41).

**Comment by amangeot** [comment] 2016-04-03 16:44
Oh. Yes you're right, I misread the PR diff ! 

There is no `NODE_ENV` in `deploy`, so no problems at all :+1:

**Comment by davezuko** [comment] 2016-04-03 20:11
Awesome, closing this for now then.

**Closed by davezuko** 2016-04-03 20:11 UTC
