### ISSUE TITLE
Location does not get updated on the Redux store LOCATION_CHANGE

### ISSUE THREAD

**Issue by KonstantinMirin** [davezuko/react-redux-starter-kit#555] opened 2016-02-13 15:56 UTC
When you call routerActions.replace action, it does put correct action to the store, but the store does not take action to update the history.
I've got this fixed by using routerMiddleware provided by react-router-redux in the following way:
```
//src/main.js
import { syncHistoryWithStore, routerMiddleware } from 'react-router-redux';
//....
const store = configureStore(initialState, routerMiddleware(browserHistory));
```
And in `src/redux/configureStore.js`
```
export default function configureStore (initialState = {}, routerMiddleware) {
  //....
  if (routerMiddleware) {
    middleware = compose(applyMiddleware(routerMiddleware), middleware)
  }
```

This way we connect routerMiddleware to the store when we configure it and everything works perfectly.

What do you think about this? Does this change make sense or I didn't get the routing working correctly for some other reason?

**Comment by davezuko** [comment] 2016-02-13 16:10
So I intentionally didn't include the middleware, primarily because I've never actually used actions to change routes and it isn't exactly necessary to `react-router-redux`. Perhaps I should just add it, though, even if it goes unused since this is the second time it's been mentioned.

**Comment by davezuko** [comment] 2016-02-13 18:58
Closing as a duplicate of https://github.com/davezuko/react-redux-starter-kit/issues/552 since it's technically not an issue, but will be opening a PR to incorporate the middleware in the base starter kit.

**Closed by davezuko** 2016-02-13 18:58 UTC
