### ISSUE TITLE
PhantomJS not liking what webpack is Babel'izing when generating test-bundler.js...

### ISSUE THREAD

**Issue by gkedge** [davezuko/react-redux-starter-kit#1084] opened 2016-11-18 23:33 UTC
I must have added something or changed something that leaks ES6'isms into test-bundler.js; PhantomJS doesn't support ES6 yet and is 'const'antly complaining about a 'const'.  Any idea how I can debug or see what is being rolled into test-bundler.js to cause this?

```
% npm test
...
PhantomJS 2.1.1 (Windows 8 0.0.0) ERROR
  SyntaxError: Unexpected token 'const'
  at webpack:///~/stringify-object/index.js:2:0 <- tests/test-bundler.js:29660
```

If an outright solution is available, I'd love it! But, I would like to know how best to see source in test-bundler too.

**Comment by dciccale** [comment] 2016-12-14 08:37
Having the exact same issue, but the weird thing is that running `npm run test:dev` does not fail.

**Comment by wwalser** [comment] 2016-12-16 06:13
I had this problem and it was because of something that I had changed. Have you changed what babel plugins are being loaded or their versions?

**Comment by davezuko** [comment] 2016-12-27 06:31
There have been a few changes since this issue was posted and I'm unable to reproduce it. I'd be super curious to hear if you're still experiencing it, but there's not much I can do about this given the current state of the project. Going to close this for now, but if you are having this issue on the latest version of master we can reopen! Thanks, sorry for the delay, and Merry Christmas!

**Closed by davezuko** 2016-12-27 06:31 UTC
