### ISSUE TITLE
The latest version doesn't start

### ISSUE THREAD

**Issue by vdzundza** [davezuko/react-redux-starter-kit#1087] opened 2016-11-20 13:51 UTC
Hi everyone,

I've cloned the master version, and when I run npm start command I've this error

EPUAKYIW0261:jony-react viktor$ npm start

> react-redux-starter-kit@3.0.0-alpha.2 start /Users/viktor/projects/jony-react
> better-npm-run start

running better-npm-run in /Users/viktor/projects/jony-react
Executing script: start

to be executed: node bin/server 
  app:webpack:config Creating configuration. +0ms
/Users/viktor/projects/jony-react/build/webpack.config.js:20
    root       : paths.client(),
                      ^

TypeError: Cannot read property 'client' of undefined
    at Object.<anonymous> (/Users/viktor/projects/jony-react/build/webpack.config.js:20:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/viktor/projects/jony-react/server/main.js:4:23)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)

npm ERR! Darwin 16.1.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.0.0
npm ERR! npm  v3.10.5
npm ERR! code ELIFECYCLE
npm ERR! react-redux-starter-kit@3.0.0-alpha.2 start: `better-npm-run start`
npm ERR! Exit status 1

**Comment by davezuko** [comment] 2016-12-01 23:17
Hey, unfortunately I cannot reproduce this, even off a fresh install. CI also does not appear to be having any trouble. There have been a few changes since this issue, so give it another shot and see if you're still encountering the problem, but I'll close this until then. Sorry about that.

**Closed by davezuko** 2016-12-01 23:17 UTC
