### ISSUE TITLE
Uncaught TypeError: Cannot read property 'instrument' of undefined

### ISSUE THREAD

**Issue by endriju** [davezuko/react-redux-starter-kit#526] opened 2016-02-07 17:01 UTC
After the last pull from master, I get following error on npm start:

Uncaught TypeError: Cannot read property 'instrument' of undefined
configureStore @ configureStore.js:15
(anonymous function) @ main.js:13
__webpack_require__ @ bootstrap 11d11fa4d959c057fa47:550
fn @ bootstrap 11d11fa4d959c057fa47:98
(anonymous function) @ app.11d11fa4d959c057fa47.js:5
__webpack_require__ @ bootstrap 11d11fa4d959c057fa47:550
webpackJsonpCallback @ bootstrap 11d11fa4d959c057fa47:21
(anonymous function) @ app.11d11fa4d959c057fa47.js:1

npm install and npm update didn't help.
Thanks!

**Comment by ericwooley** [comment] 2016-02-07 23:02
I am getting the same thing

**Comment by schpet** [comment] 2016-02-08 01:28
i was able to resolve this by replacing all instances of `require(...).default` with `require(...)`. [here's a diff](https://gist.github.com/schpet/eb8a84a1761508293930). not sure what caused this, or if my fix is legit.

**Comment by gaearon** [comment] 2016-02-08 01:33
Have you run `npm install`? The project seems to have updated to Babel 6 but if https://github.com/davezuko/react-redux-starter-kit/issues/526#issuecomment-181154312 works for you then you are using Babel 5.

**Comment by brotzky** [comment] 2016-02-08 06:16
I am getting the same error.

**Comment by avaragado** [comment] 2016-02-08 09:33
Same issue, same fix, from a fresh clone and `npm install`. `npm ls` reports babel-core 6.5.1.

**Comment by gaearon** [comment] 2016-02-08 10:03
This plugin causes behavior similar to Babel 5 (not needing to specify .default):
https://github.com/davezuko/react-redux-starter-kit/commit/c52510491c0c15e497909fa3e11e0b9bcdf36097

I don't know why it was added. Usually this plugin is used in libraries to slightly easier to consume from CommonJS environments but I don't see why one would want to use it in an app. 

If you remove this plugin, .default should work as intended.

**Comment by avaragado** [comment] 2016-02-08 10:19
Hilariously, doing that results in the inverse problem: needing to add `.default` in a number of places. Here's a diff:

```diff
diff --git a/bin/server.js b/bin/server.js
index 4bfd764..3adfe15 100644
--- a/bin/server.js
+++ b/bin/server.js
@@ -1,7 +1,7 @@
 require('babel-register')
 
-const config = require('../config')
-const server = require('../server/main')
+const config = require('../config').default
+const server = require('../server/main').default
 const debug = require('debug')('app:bin:server')
 
 const port = config.server_port
diff --git a/config/index.js b/config/index.js
index e2c2e45..a8c2fbf 100644
--- a/config/index.js
+++ b/config/index.js
@@ -21,7 +21,7 @@ try {
 // the Node process to exit if an error occurs.
 let overrides
 if (hasOverridesFile) {
-  overrides = require(`./${overridesFilename}`)(config)
+  overrides = require(`./${overridesFilename}`).default(config)
 } else {
   debug(`No configuration overrides found for NODE_ENV "${config.env}"`)
 }
diff --git a/server/main.js b/server/main.js
index acb1cb4..a032082 100644
--- a/server/main.js
+++ b/server/main.js
@@ -29,11 +29,11 @@ if (config.env === 'development') {
 
   if (config.proxy && config.proxy.enabled) {
     const options = config.proxy.options
-    app.use(convert(require('./middleware/webpack-proxy')(options)))
+    app.use(convert(require('./middleware/webpack-proxy').default(options)))
   }
 
-  app.use(require('./middleware/webpack-dev')(compiler, publicPath))
-  app.use(require('./middleware/webpack-hmr')(compiler))
+  app.use(require('./middleware/webpack-dev').default(compiler, publicPath))
+  app.use(require('./middleware/webpack-hmr').default(compiler))
 
   // Serve static assets from ~/src/static since Webpack is unaware of
   // these files. This middleware doesn't need to be enabled outside
```

**Comment by gaearon** [comment] 2016-02-08 10:24
This is pretty much expected :-)

You would need to go either one way or another. Apparently the project is in the middle state right now, and this is why it's broken.

I'd go for ES6 modules everywhere (and thus explicit .default where needed).

**Comment by avaragado** [comment] 2016-02-08 10:26
Agreed.

**Comment by davezuko** [comment] 2016-02-08 13:32
What's weird is that it's been using `require().default` for _months_ without problem, so there must have been a change in a dependency to cause this issue all of the sudden. I've been planning on removing the `add-module-exports` plugin for quite a while now but it's just been very low on the priority list. The plugin is a holdover from when this project switched to Babel 6 (which was quite early on).

**Comment by davezuko** [comment] 2016-02-08 13:36
Edit: `add-module-exports` was not even being used to transform the client-side code, it was only being used for the build system and server. Removing it either way, but I'm still at an absolute loss as to how this became an issue over night.

**Comment by davezuko** [comment] 2016-02-08 13:43
I ran an `npm update` and saw these packages changed:

```
react-redux-starter-kit@1.0.0 /Users/zuko/projects/react-redux-starter-kit
├── babel-core@6.5.1 
├── babel-loader@6.2.2 
├── babel-plugin-transform-runtime@6.5.0 
├── babel-preset-es2015@6.5.0 
├── babel-preset-react@6.5.0 
├── babel-preset-stage-0@6.5.0 
├── babel-register@6.5.1 
├── babel-runtime@6.5.0 
├── eslint-plugin-babel@3.1.0 
├── eslint-plugin-standard@1.3.2 
├── flow-interfaces@0.1.6 
├── history@2.0.0 
├── phantomjs-prebuilt@2.1.4 
├── react-redux@4.4.0 
├── react-router@2.0.0-rc6 
└── redux@3.3.1 
```

Because we were expecting `redux` to be using CommonJS modules (and therefore using `.default`) the update broke the build. Will adjust accordingly. https://github.com/rackt/redux/commit/b27cb480bca24c0bff732370d6c2bfce4f894caa

**Comment by davezuko** [comment] 2016-02-08 13:55
Confirmed it's caused by a dependency change, was working for me until I ran `npm update` and the following changed:

```
react-redux-starter-kit@1.0.0 /Users/zuko/projects/react-redux-starter-kit
├── babel-core@6.5.1 
├── babel-loader@6.2.2 
├── babel-plugin-transform-runtime@6.5.0 
├── babel-preset-es2015@6.5.0 
├── babel-preset-react@6.5.0 
├── babel-preset-stage-0@6.5.0 
├── babel-register@6.5.1 
├── babel-runtime@6.5.0 
├── eslint-plugin-babel@3.1.0 
├── eslint-plugin-standard@1.3.2 
├── flow-interfaces@0.1.6 
├── history@2.0.0 
├── phantomjs-prebuilt@2.1.4 
├── react-redux@4.4.0 
├── react-router@2.0.0-rc6 
└── redux@3.3.1 
```

Will be putting out a fix for this and then looking into what exactly broke it.

**Comment by davezuko** [comment] 2016-02-08 14:32
Fixed with https://github.com/davezuko/react-redux-starter-kit/pull/529.

**Closed by davezuko** 2016-02-08 14:32 UTC
Labels: bug

**Comment by dshamilton** [comment] 2016-02-10 11:54
Had the same issue, fixed with the suggestion from @schpet

**Comment by gaearon** [comment] 2016-02-10 14:30
Nice fix! I wonder which dep broke it.

**Comment by AshleyAitken** [comment] 2016-11-03 23:50
I'm getting this problem now (in November)?  I'm not an expert with npm but I have tried npm install and npm update to try to get the fixed versions of dependences.  Any suggestions most appreciated.

**Comment by rodrigomf24** [comment] 2017-04-14 18:48
same problem here but only on tests running on Codeship
