### ISSUE TITLE
DevTools is not logging counter actions

### ISSUE THREAD

**Issue by justingreenberg** [davezuko/react-redux-starter-kit#254] opened 2015-12-10 23:32 UTC
i don't have the time to dig into this right now but this is very strange behavior because counter state is logging correctly, and router actions and state are both logging correctly :confused: 

problem is also seen in this demo

![rrsk](https://cloud.githubusercontent.com/assets/1539088/11709543/7b8ec7c6-9ee6-11e5-8eb9-f0d9dfebdfbf.gif)

action type labels in devtools-logger were fixed in justingreenberg/react-redux-starter-kit#2: `deprecate(createConstants): babel 6 doesnt allow exports to work this way`)

**Comment by davezuko** [comment] 2015-12-11 01:14
Wait, maybe I'm just misunderstanding: is this _still_ an issue? I'm off for the night so don't have a chance to run it locally, but I'll check it out again in the morning.

**Comment by davezuko** [comment] 2015-12-12 03:13
This should be fixed. I'll reopen if you're still experiencing problems.

**Comment by justingreenberg** [comment] 2015-12-12 05:35
this is still an issue, are you not experiencing this? i did an `npm cache clean` with fresh clone and this was still happening.. using `node@5.2.0` `npm@3.3.12` tested with latest chrome and firefox

**Comment by davezuko** [comment] 2015-12-12 15:28
Nope, very strange...

![counter-demo](https://cloud.githubusercontent.com/assets/6439050/11762644/1429e878-a0bb-11e5-9cfa-407b8a74d1b6.gif)

**Comment by davezuko** [comment] 2015-12-12 15:31
I'll reopen until we can confirm that it's fixed.

**Comment by justingreenberg** [comment] 2015-12-12 18:17
@davezuko i'm seeing the same issue in your screencast... 

devtools is not logging the `action` object `{ payload: { type: "INCREMENT" } }` for increment actions, but is working properly for router actions `{ payload: { path: "/about" ... } }`

**Comment by davezuko** [comment] 2015-12-12 18:18
_Oh..._ I was still thinking you were talking about the action type not appearing, apologies for not reading more thoroughly.

**Comment by justingreenberg** [comment] 2015-12-13 19:57
can you add bug label? this is driving me nuts i have no idea what's going on

**Comment by davezuko** [comment] 2015-12-13 23:50
@justingreenberg just noticed... this isn't a bug. Look at the definition for the action:

`export const increment = () => ({ type: COUNTER_INCREMENT })`

There is no payload. I guess we could add an empty object? I tested that and it shows up, so definitely not a bug.

**Comment by justingreenberg** [comment] 2015-12-13 23:51
why didn't i think of that. we should probably include an increment value (1).

**Comment by justingreenberg** [comment] 2015-12-13 23:52
i am actually relieved and annoyed at how long i looked at createConstants and createReducer as the source of this problem

**Comment by davezuko** [comment] 2015-12-13 23:55
Hahaha, it happens to all of us. The worst bugs are the ones you spend hours working on only to realize it was something incredibly simple... like when you debug disappearing social icons for 3 hours only to realize adblock was on the whole time :sob:.

Definitely a fan of the `value` property, I'll go add that and close this once that's merged.

**Comment by davezuko** [comment] 2015-12-14 00:02
Closed with https://github.com/davezuko/react-redux-starter-kit/pull/280

**Closed by davezuko** 2015-12-14 00:02 UTC
Labels: bug
